insert into publishers (name) values ('James Bridson');
insert into authors (name) values ('James Bridson');
insert into publishers (name) values ('Ixion Software');
insert into publishers (name) values ('Tom Lindberg');
insert into authors (name) values ('Tom Lindberg');
insert into publishers (name) values ('Steve Maltz');
insert into publishers (name) values ('S.W. Thomas');
insert into authors (name) values ('S.W. Thomas');
insert into publishers (name) values ('Odyssey');
insert into authors (name) values ('James Farmer');
insert into publishers (name) values ('Adrian Smith');
insert into authors (name) values ('Adrian Smith');
insert into genres (name) values ('Glider Simulation');
insert into authors (name) values ('C.T. McGurk');
insert into authors (name) values ('Richard J. Youlden');
insert into publishers (name) values ('Adrian Stephens');
insert into publishers (name) values ('Si Greenman');
insert into genres (name) values ('Sinistar');
insert into publishers (name) values ('Computasolve');
insert into publishers (name) values ('Peter Averill');
insert into publishers (name) values ('Adrian Stephens');
insert into publishers (name) values ('Michael St. Aubyn');
insert into publishers (name) values ('APS Software');
insert into publishers (name) values ('Ian Bell');
insert into publishers (name) values ('S. Riley');
insert into publishers (name) values ('Unicorn Software');
insert into publishers (name) values ('Mastertronic Limited');
insert into publishers (name) values ('Warlock Computer Software');
insert into publishers (name) values ('Paul Newell');
insert into publishers (name) values ('Epsilon Software');
